In [28]:
#import the NumPy Library
import numpy as np

#making the random array and assigning it to X
X = np.random.random((5,5))
print("Random Array X: \n",X,"\n")

avg = np.mean(X)
sd = np.std(X)

#making a room for the normalized array
Z = np.zeros((5,5))
x = 0
y = 0

#Nested loop to change the Zero Array with the Normalized Values using the Z formula
while y < 5:
    while x < 5:
        Z[x,y] = (avg-(X[x,y]))/sd
        x+=1
    y+=1
    #Reset x
    x=0

print("Normalized Array Z: \n",Z)
np.save('X_normalized',Z)

Random Array X: 
 [[0.21955276 0.99587019 0.7721965  0.82036682 0.87108597]
 [0.61438509 0.22111771 0.73559455 0.24995759 0.07755459]
 [0.20094918 0.64504856 0.43149235 0.64030493 0.49391684]
 [0.60243394 0.76961348 0.6701408  0.71441299 0.94897453]
 [0.30358079 0.65317177 0.74894459 0.21194078 0.92895414]] 

Normalized Array Z: 
 [[ 1.37054273 -1.5677277  -0.72114899 -0.90346801 -1.09543405]
 [-0.12385131  1.36461958 -0.58261491  1.25546403  1.90798915]
 [ 1.44095511 -0.23990896  0.56837623 -0.22195488  0.33210687]
 [-0.07861761 -0.71137258 -0.33488014 -0.50244521 -1.3902331 ]
 [ 1.05250648 -0.27065437 -0.63314327  1.39935318 -1.31445827]]
